# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 08:07
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160420_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone (optional)'),
        ),
        migrations.AddField(
            model_name='user',
            name='www_site',
            field=models.CharField(blank=True, max_length=30, verbose_name='Personal website address (optional)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_image',
            field=models.ImageField(blank=True, upload_to=account.models.normalization_file_name, verbose_name='Portfile photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=2048, verbose_name='Bio (optional)'),
        ),
    ]
