# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session'),
        ),
    ]
