# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160420_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='visit_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
