# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20160420_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlog',
            options={'ordering': ('-visit_datetime', 'id')},
        ),
    ]
