# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20160420_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlog',
            options={'ordering': ['-visit_datetime', 'id']},
        ),
    ]
