# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 05:54
from __future__ import unicode_literals

import customer.tags
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20160621_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tags',
            field=customer.tags.TagField(base_field=models.CharField(max_length=50), blank=True, size=None),
        ),
    ]
