# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_html', models.TextField(max_length=2048, verbose_name='Description')),
                ('title', models.TextField(max_length=254, verbose_name='Title')),
            ],
        ),
    ]
