# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Product',
        ),
    ]
