# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 13:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopifier_admin', '0003_auto_20161221_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
