# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-23 07:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import shopifier.admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifier_admin', '0004_auto_20161221_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=15, verbose_name='Barcode (ISBN, UPC, GTIN, etc.)')),
                ('compare_at_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Compare at price)')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('fulfillment_service', models.CharField(choices=[('manual', 'Manual'), ('choice_fulfillment', 'Choice Fulfillment')], default='manual', max_length=15, verbose_name='FULFILLMENT SERVICE')),
                ('grams', models.IntegerField(default=0, verbose_name='Weight')),
                ('inventory_management', models.CharField(blank=True, choices=[('', "Don't track inventory"), ('shopifier', "Shopifier tracks this product's inventory")], default='shopifier', max_length=15, verbose_name='Inventory policy')),
                ('inventory_policy', models.CharField(choices=[('deny', 'deny'), ('continue', 'continue')], default='deny', max_length=15, verbose_name="Allow customers to purchase this product when it's out of stock")),
                ('inventory_quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('old_inventory_quantity', models.IntegerField(default=0)),
                ('inventory_quantity_adjustment', models.IntegerField(default=0)),
                ('option', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('position', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price)')),
                ('requires_shipping', models.BooleanField(default=True, verbose_name='This product requires shipping')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU (Stock Keeping Unit)')),
                ('taxable', models.BooleanField(default=False, verbose_name='Charge taxes on this product')),
                ('title', models.TextField(blank=True, max_length=254, verbose_name='Title')),
                ('updated_at', models.DateTimeField(default=shopifier.admin.models.now)),
                ('weight', models.FloatField(default=0, verbose_name='Weight')),
                ('weight_unit', models.CharField(choices=[('lb', 'lb'), ('oz', 'oz'), ('kg', 'kg'), ('g', 'g')], default='kg', max_length=5)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shopifier_admin.ProductImage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shopifier_admin.Product')),
            ],
        ),
    ]
