# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-07 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifier_admin', '0004_auto_20161207_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=254, verbose_name='Image alt text'),
        ),
    ]
