# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-26 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifier_admin', '0005_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='option',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='option1',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='option2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='option3',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
