# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-12 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifier_admin', '0006_auto_20161212_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='body_html',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Description'),
        ),
    ]
