# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-20 05:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import shopifier.admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifier_admin', '0007_auto_20161212_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='body_html',
            field=models.TextField(default=datetime.datetime(2016, 12, 20, 5, 0, 14, 371187, tzinfo=utc), max_length=2048, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='src',
            field=models.ImageField(upload_to=shopifier.admin.models.normalization_img_file_name),
        ),
    ]
