# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-17 02:56
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifier_admin', '0010_user_receive_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=['full'], size=None),
        ),
    ]
