# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-17 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifier_admin', '0011_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
