# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-28 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shopifier.admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifier_admin', '0014_auto_20170128_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('position', models.IntegerField()),
                ('updated_at', models.DateTimeField(default=shopifier.admin.models.now)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopifier_admin.CustomCollection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='shopifier_admin.Product')),
            ],
        ),
    ]
