# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-28 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopifier_admin', '0015_collect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to='shopifier_admin.CustomCollection'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to='shopifier_admin.Product'),
        ),
    ]
