# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-28 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shopifier.admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifier_admin', '0016_auto_20170128_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=shopifier.admin.models.normalization_img_collection_file_name)),
                ('created_at', models.DateTimeField(default=shopifier.admin.models.now)),
            ],
        ),
        migrations.AlterField(
            model_name='customcollection',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='shopifier_admin.CollectionImage'),
        ),
    ]
