# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-30 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifier_admin', '0017_auto_20170128_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcollection',
            name='title',
            field=models.TextField(blank=True, max_length=254, verbose_name='Title'),
        ),
    ]
