# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-30 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import shopifier.admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifier_admin', '0019_auto_20170130_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionimage',
            name='src',
            field=models.ImageField(null=True, upload_to=shopifier.admin.models.normalization_img_collection_file_name),
        ),
    ]
