# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-30 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopifier_admin', '0020_auto_20170130_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcollection',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='shopifier_admin.CollectionImage'),
        ),
    ]
